Repository Juniper/ansible-junos-stdlib, pull requests merged in 2019-09, with the labels that each got.

#435 Fixes issue #434
  library/juniper_junos_rpc.py
Labels: Status: Accepted

#451 remove requirements.txt file
  requirements.txt
Labels: Priority: Low, Status: In Progress, Type: Bug

#433 Fix ansible lint
  meta/main.yml
Labels: Status: Accepted

#429 Openconfig and yang supports in juniper_junos_config module
  library/juniper_junos_config.py
  module_utils/juniper_junos_common.py
Labels: Status: Accepted

#428 Add support for ignore_warning in juniper_junos_common/open_configuration
  library/juniper_junos_config.py
  module_utils/juniper_junos_common.py
Labels: Priority: Low, Status: Accepted, Type: Enhancement

#427 --diff is not working correctly
  library/juniper_junos_config.py
Labels: Status: Accepted

#416 Adds ansible-junos-awx project
  ansible-junos-awx/Makefile
  ansible-junos-awx/Makefile.variable
  ansible-junos-awx/README.md
Labels: Status: Accepted
